---
# Per environment values which override defaults in hmpps-alerts-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: alerts-ui-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    INGRESS_URL: "https://alerts-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    ALERTS_API_URL: "https://alerts-api-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod # sent to Slack channel #move-and-improve-alerts-non-prod
  businessHoursOnly: true
