enum AuthorisedRoles {
  ROLE_ALERTS_REFERENCE_DATA_MANAGER = 'ROLE_ALERTS_REFERENCE_DATA_MANAGER',
  ROLE_BULK_PRISON_ESTATE_ALERTS = 'ROLE_BULK_PRISON_ESTATE_ALERTS',
}

export default AuthorisedRoles
