enum AuthorisedRoles {
  ROLE_ALERTS_REFERENCE_DATA_MANAGER = 'ROLE_ALERTS_REFERENCE_DATA_MANAGER',
  ROLE_BULK_PRISON_ESTATE_ALERTS = 'ROLE_BULK_PRISON_ESTATE_ALERTS',
  ROLE_DPS_APPLICATION_DEVELOPER = 'ROLE_DPS_APPLICATION_DEVELOPER',
}

export default AuthorisedRoles
