name: Upload coverage report

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  coverage:
    name: Upload coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: test_artifacts
          pattern: '*test_artifacts'
          merge-multiple: true
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          use_oidc: true
          directory: test_artifacts
          report_type: coverage
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          use_oidc: true
          directory: test_artifacts
          report_type: test_results
